export const PROPERTY_TYPES = [
  'Self Contain',
  'Mini Flat',
  '1 Bedroom',
  '2 Bedroom',
  '3 Bedroom',
  'Room and Parlour',
  'Shared Room',
  'Bungalow',
  'Duplex',
  'Others'
]

// Stages both parties must independently confirm before they count.
export const NEGOTIATION_STAGES = [
  { key: 'available', label: 'Available', order: 1 },
  { key: 'viewing_scheduled', label: 'Viewing Scheduled', order: 2 },
  { key: 'price_agreed', label: 'Price Agreed', order: 3 },
  { key: 'deposit_paid', label: 'Deposit Paid', order: 4 },
  { key: 'moved_in', label: 'Moved In', order: 5 },
  { key: 'vacated', label: 'Vacated', order: 6 }
]

// Stages at which a property should be auto-hidden from public search.
// Available and Viewing Scheduled stay visible; Vacated becomes visible again.
export const HIDDEN_AT_STAGES = ['price_agreed', 'deposit_paid', 'moved_in']

export const NIGERIAN_UNIVERSITIES = [
  'Abia State University',
  'Achievers University',
  'Adamawa State University',
  'Adekunle Ajasin University',
  'Afe Babalola University',
  'Ahmadu Bello University',
  'Air Force Institute of Technology',
  'Ajayi Crowther University',
  'Akwa Ibom State University',
  'Al-Hikmah University',
  'Ambrose Alli University',
  'American University of Nigeria',
  'Babcock University',
  'Bauchi State University',
  'Bayero University Kano',
  'Baze University',
  'Bells University of Technology',
  'Benson Idahosa University',
  'Benue State University',
  'Bingham University',
  'Bowen University',
  'Caleb University',
  'Chukwuemeka Odumegwu Ojukwu University',
  'Covenant University',
  'Crawford University',
  'Cross River University of Technology',
  'Delta State University',
  'Ebonyi State University',
  'Edo State University',
  'Ekiti State University',
  'Elizade University',
  'Enugu State University of Science and Technology',
  'Federal University of Agriculture, Abeokuta',
  'Federal University of Petroleum Resources',
  'Federal University of Technology, Akure',
  'Federal University of Technology, Minna',
  'Federal University of Technology, Owerri',
  'Federal University, Dutse',
  'Federal University, Dutsin-Ma',
  'Federal University, Gashua',
  'Federal University, Gusau',
  'Federal University, Kashere',
  'Federal University, Lafia',
  'Federal University, Lokoja',
  'Federal University, Ndufu-Alike',
  'Federal University, Otuoke',
  'Federal University, Oye-Ekiti',
  'Federal University, Wukari',
  'Igbinedion University',
  'Imo State University',
  'Kaduna State University',
  'Kano University of Science and Technology',
  'Kebbi State University of Science and Technology',
  'Kogi State University',
  'Kwara State University',
  'Ladoke Akintola University of Technology',
  'Lagos State University',
  'Landmark University',
  'Michael Okpara University of Agriculture',
  'Modibbo Adama University',
  'Nasarawa State University',
  'National Open University of Nigeria',
  'Niger Delta University',
  'Nnamdi Azikiwe University',
  'Obafemi Awolowo University',
  'Ogun State Institute of Technology',
  'Olabisi Onabanjo University',
  'Osun State University',
  'Pan-Atlantic University',
  'Rivers State University',
  'Redeemer\'s University',
  'Sokoto State University',
  'Tai Solarin University of Education',
  'Taraba State University',
  'University of Abuja',
  'University of Africa, Toru-Orua',
  'University of Agriculture, Makurdi',
  'University of Benin',
  'University of Calabar',
  'University of Ibadan',
  'University of Ilorin',
  'University of Jos',
  'University of Lagos',
  'University of Maiduguri',
  'University of Medical Sciences, Ondo',
  'University of Nigeria, Nsukka',
  'University of Port Harcourt',
  'University of Uyo',
  'Usmanu Danfodiyo University',
  'Veritas University',
  'Wellspring University',
  'Yaba College of Technology',
  'Others'
]

export const VISIT_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  COMPLETED: 'completed'
}
